apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: booknexus
spec:
  replicas: 1                 # One instance for now
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: booknexus-backend:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          envFrom:
            - configMapRef:
                name: backend-config

          # Liveness Probe
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 60 #Wait before the first check
            periodSeconds: 10 # check every 10 sec
            timeoutSeconds: 5
            failureThreshold: 3 #fail 3 times-> then restart

          #Readiness probe
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3