apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: booknexus
spec:
  replicas: 1                 # One instance for now
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: booknexus-backend:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          envFrom:
            - configMapRef:
                name: backend-config
