apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: booknexus
spec:
  type: ClusterIP  # Change from NodePort
  selector:
    app: backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000