apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: booknexus
spec:
  type: ClusterIP  # Change from NodePort  
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80